export const USER_CHANGED = 'USER_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const CLEAR_FIELDS = 'CLEAR_FIELDS';
export const LOADING_PROPS = 'LOADING_PROPS';
export const GET_TOP_READERS = 'GET_TOP_READERS';
export const GET_TOP_REVIEWERS = 'GET_TOP_REVIEWERS';
